### ISSUE TITLE
can't process big log : out of memory

### ISSUE THREAD

**Issue by lalop** [bnoordhuis/node-profiler#15]
I launch my app with --prof and the result is a 1G file.
When I try to process it with nprof I get this error :
FATAL ERROR: CALL_AND_RETRY_0 Allocation failed - process out of memory

**Comment by amark** [comment]
@bnoordhuis thanks for all your awesome work!

Is there any update on this? When I split my log with that (or other commands) only the 1st log works with `node --prof-process --preprocess -j`, all the other "later" logs don't process correctly - but those are the ones I need to look at.

I regularly have 1GB+ logs that I need to inspect only the tail end.

I'm guessing there is a simple fix I'm missing now in 2020? Any links/tips/pointers would be super appreciated.

Thank you!!!

**Comment by bnoordhuis** [comment]
@amark With modern versions of Node.js, the `--max_old_space_size=...` trick should work.

Old Node versions had a bug where values beyond 1.5G didn't really work but nowadays setting it to 4096 or 8192 (or even bigger) should Just Work.

If that doesn't help, can you open an issue over at nodejs/node and cc me? Cheers.
