### ISSUE TITLE
Incompatible with v0.12

### ISSUE THREAD

**Issue by laggingreflex** [bnoordhuis/node-profiler#18]
I updated to node 0.12 and it stopped working. So I tried to install again and it seems to fail to install

    $ npm install -g profiler
    /usr/local/bin/nprof -> /usr/local/lib/node_modules/profiler/nprof

    > profiler@1.2.3 install /usr/local/lib/node_modules/profiler
    > node-gyp rebuild

    child_process: customFds option is deprecated, use stdio instead.
    make: Entering directory `/usr/local/lib/node_modules/profiler/build'
      ACTION binding_gyp_nprof_target_nprof Release/nprof
      SOLINK_MODULE(target) Release/obj.target/nprof.node
      SOLINK_MODULE(target) Release/obj.target/nprof.node: Finished
      COPY Release/nprof.node
      CXX(target) Release/obj.target/profiler/profiler.o
    ../profiler.cc:9: error: ISO C++ forbids declaration of ‘Arguments’ with no type
    ../profiler.cc:9: error: expected ‘,’ or ‘...’ before ‘&’ token
    ../profiler.cc: In function ‘v8::Handle<v8::Value><unnamed>::GC(int)’:
    ../profiler.cc:10: error: ‘IdleNotification’ is not a member of ‘v8::V8’
    /root/.node-gyp/0.12.0/deps/v8/include/v8.h:6606: error: too few arguments to function ‘v8::Handle<v8::Primitive> v8::Undefined(v8::Isolate*)’
    ../profiler.cc:11: error: at this point in file
    ...
    ../profiler.cc:45: error: ‘New’ is not a member of ‘v8::String’
    ../profiler.cc:46: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(int))’
    /root/.node-gyp/0.12.0/deps/v8/include/v8.h:3455: note: candidates are: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, void (*)(const v8::FunctionCallbackInfo<v8::Value>&), v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)
    make: *** [Release/obj.target/profiler/profiler.o] Error 1
    make: Leaving directory `/usr/local/lib/node_modules/profiler/build'
    gyp ERR! build error
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
    gyp ERR! System Linux 2.6.32-504.8.1.el6.x86_64
    ...
    npm ERR! profiler@1.2.3 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the profiler@1.2.3 install script 'node-gyp rebuild'.

[full error](http://pastebin.com/d5cFEpfA)

**Comment by laggingreflex** [comment]
I updated to iojs and it works. Although till not installing. Maybe it's an error on my part, hmm. Closing for now.

**Comment by bnoordhuis** [comment]
@laggingreflex Are you installing it for the nprof script or the add-on?  The latter is effectively incompatible with the versions of V8 in node.js v0.12 and io.js because most of the relevant APIs have been removed.  If you want a programmatic profiler, you may want to take a look at our [strong-agent](https://npmjs.org/package/strong-agent) product.
